### ISSUE TITLE
`latest` version does not reflect Age's recent 1.0.0 release

### ISSUE THREAD

**Issue by jpluscplusm** [threkk/asdf-age#1]
**Describe the bug**

This plugin believes that age v1.0.0-rc.3 is the latest version available, even though it knows that 1.0.0 has been released.

**Steps to reproduce**

- Register the plugin
- List the available versions, seeing that 1.0.0 is available
- Install the `latest` version of age
- End up with age version 1.0.0-rc.3

**Expected behavior**

Plugin should prefer `1.0.0` over `1.0.0-rc.<anthing>`

**Screenshots**

```
$ age
-bash: age: command not found
$ asdf plugin add age https://github.com/threkk/asdf-age.git
$ asdf list-all age
1.0.0-beta1
1.0.0-beta2
1.0.0-beta3
1.0.0-beta4
1.0.0-beta5
1.0.0-beta6
1.0.0-beta7
1.0.0
1.0.0-rc.1
1.0.0-rc.2
1.0.0-rc.3
$ asdf install age latest
* Downloading age release 1.0.0-rc.3 from https://github.com/FiloSottile/age/releases/download/v1.0.0-rc.3/age-v1.0.0-rc.3-linux-amd64.tar.gz
age 1.0.0-rc.3 installation was successful!
$ asdf global age latest
$ age --version
v1.0.0-rc.3
```

**Additional context**

```
$ ( cd ~/.software/asdf/plugins/age/ ; git log --oneline -1 )
cbf0c71 (HEAD -> master, origin/master, origin/HEAD) ci: Retry ci
$ asdf --version
v0.9.0-9ee24a3
```

I suspect this problem will disappear once Age releases any version after 1.0.0, but I've not checked that this will happen.

**Comment by threkk** [comment]
I am sorry, I totally missed this issue (for some reason, Github decided to not notify me about it). Thanks for the heads up, I will look into it ASAP.

**Comment by threkk** [comment]
The issue has been fixed :)

In order to pull the latest changes, run `asdf plugin update age`.
